name = "unirep-window"
type = "javascript"
account_id = ""
workers_dev = true
zone_id = ""
compatibility_date = "2022-02-16"

kv_namespaces = [
  { binding = "UNIREP_DATA", id = "ff4ba4b18aa74bceb04d5a02e575c19b" }
]

[site]
bucket = "build"
entry-point = "dist"

[build]
command = "npm run build:worker && echo '{\"name\": \"unirep-window\",\"main\":\"index.js\"}' > dist/package.json"

[build.upload]
format = "service-worker"
